spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  datasource:
#    url: jdbc:h2:tcp://localhost/~/test
    url: jdbc:h2:tcp://localhost/~/test
    username: SA
    driver-class-name: org.h2.Driver
    initialization-mode: always